### ISSUE TITLE
How to stop hands from attaching to VR headset in VR?

### ISSUE THREAD

**Issue by janimationd** [getnamo/leap-ue4#18]
Hi, I'm trying to make a VR environment with a table-mounted Leap Motion (please trust me, I need to do it).

Is it possible to tell the plugin to stop snapping the hand models' transforms to the VR headset's position, and instead have them relative to some static position?

**Comment by getnamo** [comment]
Neat use case. To stop auto-adjustment you should look into calling _OptimizeForHMD_ function (https://github.com/getnamo/leap-ue4/blob/master/Plugins/LeapMotion/Source/LeapMotion/Public/LeapController.h#L68) on the _LeapController_ Component. Reverse the default switches to get the behavior you're expecting. Let me know if you run into any bugs on this one.
