### ISSUE TITLE
ok I have the htc vive with the leap vr bundle can get it to som what work with the htc however trying to get it to work with steams big screen beta any suggestions 

### ISSUE THREAD

**Issue by reds088** [getnamo/leap-ue4#23]
any help would be appreciated. am trying to use leap motion in big screen beta on steam, is there and help or code that some one can suggest to say use leap motion hand controls such as handwave and type on the keyboard in big screen beta.

**Comment by getnamo** [comment]
is this in any way related to leap motion unreal engine plugin v2.0?

**Comment by reds088** [comment]
I have been looking for any info I can find I don't know if the code exist yet due to the fact that big screen is still in beta.

**Comment by reds088** [comment]
according to : https://developer.leapmotion.com/documentation/v2/unreal/index.html it is supported by win 7-8 no thing about 10

**Comment by reds088** [comment]
What I am looking for is not for unreal however, It is for steam Big screen beta

**Comment by reds088** [comment]
got leap working with big screen some what, https://github.com/cbuchner1/driver_leap , 
however it only shows one hand, the right hand, even when it picks up left it shows it as a right hand and only shows one hand.

**Comment by getnamo** [comment]
See http://bigscreenvr.com/help/

This is not the right place for support for that application, refer to app developers support page.
