### ISSUE TITLE
How to use it in a C++ project?

### ISSUE THREAD

**Issue by zhudongwork** [getnamo/leap-ue4#24]
Thanks for your work on this plugin.
If I have to use the C++ instead of blueprint  ,how to use the Leap plugin and start my project?Could you help me?

**Comment by getnamo** [comment]
message me on unreal forums for preview build of modern rewrite plugin which supports C++

**Comment by getnamo** [comment]
also related to https://github.com/getnamo/leap-ue4/issues/22
