### ISSUE TITLE
Leap 现在能不能实现在Android VR一体机上交互

### ISSUE THREAD

**Issue by cunxinshou** [getnamo/leap-ue4#29]
不知道能不能在PICOAndroid一体机上实现交互，我们公司现在想要这个功能。

**Comment by getnamo** [comment]
Re-open in English.

**Comment by cunxinshou** [comment]
> 用英语重新开放。

Sorry,Can Leap interact on the Android VR machine?

**Comment by getnamo** [comment]
Not supported in the old plugin (which this repository is), and currently not yet supported in https://github.com/leapmotion/leapunreal which is the new repository location.
